### ISSUE TITLE
exchange 2

### ISSUE THREAD

**Issue by damian568** [damian568/SequenceManager#1]
exchange {index} – разделя поредицата от тази позиция и обръща двете под-поредици. Например поредицата “6 4 7 8 9 5 8 6” при “exchange 2” трябва да се раздели от втора позиция (числото 8) на две подпоредици (6 4 7) и (8 9 5 8 6), като крайният резултат е “8 9 5 8 6 6 4 7”. Оригиналната поредица трябва да се промени на новата и новата да се напечата на стандартния изход (конзолата). 

Качваш кога в Еxchange бранча.

**Comment by alpavlinov04** [comment]
using System;

namespace Zadacha
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hi this is exchange 1");
            int[] myNum = { 6, 4, 7, 8, 9, 5, 8, 6 };
            for (int i = 0; i < myNum.Length; i++)
            {
                Console.WriteLine(myNum[i]);
            }
            Console.WriteLine("This is exchange 2");
            Console.ReadLine();
            int[] myNum2 = { 8, 9, 5, 8, 6, 6, 4, 7 };
            for (int i = 0; i < myNum2.Length; i++)
            {
                Console.WriteLine(myNum2[i]);
            }

        }
    }
}
